service: service1

frameworkVersion: "3"

plugins:
  - serverless-bundle
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /hello
