service: service2
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /hello
